FROM node:14-alpine as build

WORKDIR /app

COPY package.json ./

RUN yarn install --silent --frozen-lockfile

COPY . .

RUN yarn build

FROM nginx:1.9.15-alpine

COPY --from=build /app/build /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
